default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: wallet_manager
  username: root
  password: root
  host: db

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default