version: "3.9"
services:
  app:
    container_name: app
    image: jaredosuna/wallet_manager_api:latest
    depends_on:
      - db
    volumes:
      - .:/curso-rails
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_NAME=wallet_manager
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - RAILS_SERVE_STATIC_FILES=true
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  db-data:
    driver: local
  db:
    driver: local